### ISSUE TITLE
Does it have buffer view support ?

### ISSUE THREAD

**Issue by gokulpulikkal** [zattoo/TvOSSlider#11]
I could not find a view that can be used for showing the user how much the video is buffered

**Comment by lechium** [comment]
@gokulpulikkal you might want to keep an eye on my obj-c port of this. im still actively updating it and have started to add something along those lines. https://github.com/lechium/KBSlider

**Comment by dcordero** [comment]
TvOSSlider has been implemented with the same public API as UISlider for iOS, which does not have this kind of features.
If you need a slider with a supplementary view to show thumbnails in a video player, I recommend you creating a fork and adjusting it to your needs.
